[INFO 19:09:55] my_main *******************
[INFO 19:09:55] my_main WANDB RUN ID:
[INFO 19:09:55] my_main lrkmax1l
[INFO 19:09:55] my_main *******************
/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/stdout_capturing.py:179: UserWarning: tee_stdout.wait timeout. Forcibly terminating.
  warnings.warn("tee_stdout.wait timeout. Forcibly terminating.")
/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/sacred/stdout_capturing.py:185: UserWarning: tee_stderr.wait timeout. Forcibly terminating.
  warnings.warn("tee_stderr.wait timeout. Forcibly terminating.")
[DEBUG 19:09:57] pymarl Stopping Heartbeat
[ERROR 19:09:57] pymarl Failed after 0:00:05!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/main.py", line 44, in my_main
    run(_run, config, _log)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/run.py", line 67, in run
    run_sequential(args=args, logger=logger)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/run.py", line 138, in run_sequential
    mac = mac_REGISTRY[args.mac](buffer.scheme, groups, args)
  File "/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/src/controllers/basic_controller.py", line 50, in __init__
    max_steps=args.max_steps,
AttributeError: 'types.SimpleNamespace' object has no attribute 'max_steps'
